# email_sender.py

from __future__ import annotations

import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from io import BytesIO

from config import Config


def send_pdf_email(
    recipient: str,
    pdf_buffer: BytesIO,
    project_title: str,
    audience_type: str,
) -> None:
    """Send a PDF report to a single recipient via SMTP.

    Raises
    ------
    ValueError
        If SMTP is not configured.
    smtplib.SMTPException
        On delivery failure.
    """
    if not Config.SMTP_HOST or not Config.SMTP_USER or not Config.SMTP_PASSWORD:
        raise ValueError(
            "SMTP is not configured. Set SMTP_HOST, SMTP_USER, and SMTP_PASSWORD "
            "in your environment or .env file."
        )

    label = "Stakeholder Report" if audience_type == "stakeholder" else "Engineering Report"
    subject = f"FlowForge {label}: {project_title}"
    body = (
        f"Please find the FlowForge {label} for '{project_title}' attached.\n\n"
        "Generated by FlowForge — AI-powered project planning."
    )

    msg = MIMEMultipart()
    msg["From"] = Config.SMTP_USER
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    pdf_buffer.seek(0)
    attachment = MIMEApplication(pdf_buffer.read(), _subtype="pdf")
    filename = f"flowforge_{audience_type}_report.pdf"
    attachment.add_header("Content-Disposition", "attachment", filename=filename)
    msg.attach(attachment)

    with smtplib.SMTP(Config.SMTP_HOST, Config.SMTP_PORT) as server:
        server.ehlo()
        if Config.SMTP_USE_TLS:
            server.starttls()
            server.ehlo()
        server.login(Config.SMTP_USER, Config.SMTP_PASSWORD)
        server.sendmail(Config.SMTP_USER, recipient, msg.as_string())
